//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.CasesToDoctors = new HashSet<CasesToDoctor>();
            this.HelpCalls = new HashSet<HelpCall>();
            this.Contacts = new HashSet<Contact>();
        }
    
        public string doctorId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string doctorPhone { get; set; }
        public string address { get; set; }
        public byte[] pictureDiploma { get; set; }
        public bool isConfirmed { get; set; }
        public string mail { get; set; }
        public System.DateTime certificateValidity { get; set; }
        public string certificateNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasesToDoctor> CasesToDoctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HelpCall> HelpCalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contacts { get; set; }
    }
}
