//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpCall
    {
        public int callId { get; set; }
        public int caseId { get; set; }
        public string doctorId { get; set; }
        public double addressX { get; set; }
        public double addressY { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
